version: '3'
services:
  recycler:
    image:
      willnx/vlab-recycler
    restart:
      unless-stopped
    volumes:
      - ./recycler:/usr/lib/python3.6/site-packages/recycler
      - /etc/vlab:/etc/vlab
    environment:
      - INF_VCENTER_SERVER=ChangeMe
      - INF_VCENTER_USER=ChangeMe
      - INF_VCENTER_PASSWORD=ChangeMe
      - AUTH_PRIVATE_KEY_LOCATION=/etc/vlab/ChangeMe
      - AUTH_TOKEN_ALGORITHM=RS256
      - AUTH_LDAP_URL=ldaps://ChangeMe
      - AUTH_BIND_USER=ChangeMe
      - AUTH_BIND_PASSWORD_LOCATION=/etc/vlab/ChangeMe
      - AUTH_SEARCH_BASE=ChangeMe
      - VLAB_URL=https://ChangeMe
      - VLAB_IP=ChangeMe
